alunos = ["joao.aluno@exemplo.com",
"maria.aluno@exemplo.com",
"pedro.aluno@exemplo.com",
"ana.aluno@exemplo.com",
"jose.aluno@exemplo.com",
"lucas.aluno@exemplo.com",
"anaclara.aluno@exemplo.com",
"carlos.aluno@exemplo.com",
"juliana.aluno@exemplo.com",
"paulo.aluno@exemplo.com",
"rafaela.aluno@exemplo.com",
"lucasalves.aluno@exemplo.com",
"julianacosta.aluno@exemplo.com",
"rodrigo.aluno@exemplo.com",
"gabriela.aluno@exemplo.com",
"marcos.aluno@exemplo.com",
"fernanda.aluno@exemplo.com",
"carla.aluno@exemplo.com",
"andre.aluno@exemplo.com",
"lucasferreira.aluno@exemplo.com"]


professores = ["joao.professor@exemplo.com",
"maria.professor@exemplo.com",
"pedro.professor@exemplo.com",
"ana.professor@exemplo.com",
"jose.professor@exemplo.com",
"lucas.professor@exemplo.com",
"anaclara.professor@exemplo.com",
"carlos.professor@exemplo.com",
"juliana.professor@exemplo.com",
"paulo.professor@exemplo.com",
"rafaela.professor@exemplo.com",
"lucasalves.professor@exemplo.com",
"julianacosta.professor@exemplo.com",
"rodrigo.professor@exemplo.com",
"gabriela.professor@exemplo.com",
"marcos.professor@exemplo.com",
"fernanda.professor@exemplo.com",
"carla.professor@exemplo.com",
"andre.professor@exemplo.com",
"lucasferreira.professor@exemplo.com",
"henrique.cunha@ifpb.edu.br"]